### PR TITLE
Midproject

### PR DESCRIPTION
**Pull request by yfeng46**
Codes are in the src/ folder.
https://github.com/yfeng46/SongAnalytics/tree/master/src

download.py: code for downloading data from S3 bucket. Need to provide the csv file name as well as the output path
upload.py: code for uploading data to S3 bucket. Need to provide the input file path, S3 bucket and the output file path
tables.py: create three data table -- lyrics, wiki_hot_100s and billboard_tracks that the model will use

### CODE REVIEW

**Comment by yzelac** [comment]
Hi Joyce, could you provide an example command for running your download.py? Thanks!

**Comment by yfeng46** [comment]
For download:
python download.py --file_name_to_download --output_file_path

For upload:
python upload.py --input_file_path --bucket_name --output_file_name

For tables:
python tables.py
It will create three tables that my model will use: lyrics, wiki_hot_100s and billboard_tracks

**Comment by yzelac** [comment]
Hi Joyce, can you also provide the name of the files in the public S3 bucket? Once you decide which files you may need for the project, it would be great to incorporate the file names within your code. In this way, users will only need to specify the  "output_file_path" when running "download.py".

**Comment by yfeng46** [comment]
I have three database that the model will use: lyrics.csv, spotify_track_data.csv, and wiki_hot_100s. I have that arguments there just to let the user to download whichever they want to.

**Comment by yfeng46** [comment]
I'll add the default arguments there

**Comment by yzelac** [comment]
Great, it would be wonderful if you can also update the "Running the application" in your READ.ME file.

**Comment by yzelac** [comment]
requirements.txt is missing pandas and pymysql package

**Comment by yfeng46** [comment]
Good catch and the requirements.txt should be complete now

**Comment by yzelac** [comment]
Please add documentation of the codes when necessary for interpretability. Also, consider adding some logging as well.

**Comment by yfeng46** [comment]
Will do!

**Comment by yzelac** [comment]
Seem like your requirements.txt also includes "requirement pkg-resources==0.0.0", which turned out would cause an error when installing the requirements.txt. Per research, I found it might be safe to remove the line in the text file. 

For your reference:
https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by yfeng46** [comment]
Interesting. I'll take a look into it

**Comment by yzelac** [comment]
Also, boto3 should be included in the req file as well :)

**Comment by yzelac** [comment]
Also, should "import logging" in download.py :))))

**Comment by yzelac** [comment]
For consistency, please change 'default="../data/"' in download.py to  `default="/data/` and require user to run all the code from the root directory of the repo in READ.ME.

**Comment by yfeng46** [comment]
Change the code as suggested and I'll update the README.md soon

**Comment by yzelac** [comment]
Functionality:
- All codes are working well right now. I am able to download the data, upload data to my S3, and added the tables to my RDS 'msia423' database.

Readability and code quality
- Code is easy to follow and functions are concise and efficient.
- The default arguments help users work with the code a lot.

Overall design:
- The design works efficiently. The code is modular and extensible for the rest of the project.

Testing:
- The code is structured and can be easily tested.

Documentation:
- Logging and docstrings are included in all python files. The documentation is well-writer and all parameter names make sense to users.
- The READ.ME is updated and explain the design and how to run the code effectively. 
- Commitment statements are mostly meaningful.

I think the PR is ready for merging!

**Comment by yfeng46** [comment]
Thanks for the review here!

**Pull request merged**
